[dlg ModMenuName]
Amicitia Mod Menu[w][e]

[sel ModMenu]
[s]Player[f 4 26 0 94][e]
[s]Battle Select[f 4 26 1 95][e]
[s]Teleport[f 4 26 2 96][e]
[s]Sound Test[f 4 26 3 97][e]
[s]Field Select[f 4 26 4 98][e]
[s]Event Select[f 4 26 5 99][e]
[s]Camera[f 4 26 6 100][e]
[s]NPCs[f 4 26 7 101][e]
[s]Flags[f 4 26 8 102][e]
[s]Calendar[f 4 26 9 103][e]
[s]Movie Select[f 4 26 10 104][e]
[s]Check Phone/Auto Recover[f 4 26 11 105][e]
[s]About[f 4 26 12 106][e]

[dlg GENERIC_HELP_94]
[s]Edit your Personas, items, stats,[n]money, or even your name.[e]

[dlg GENERIC_HELP_95]
[s]Choose a type of battle[n]to start, then begin[n]the fight![e]

[dlg GENERIC_HELP_96]
[s]Clip through walls and explore[n]out of bounds areas. Hold[n]Square to change axis.[e]

[dlg GENERIC_HELP_97]
[s]Select a BGM ID to[n]play back an audio track.[e]

[dlg GENERIC_HELP_98]
[s]Enter the ID of a field pack[n]to warp to that map.[e]

[dlg GENERIC_HELP_99]
[s]Enter the ID of an event pack[n]to start the event.[e]

[dlg GENERIC_HELP_100]
[s]Change the camera's position,[n]rotation, and field of view.[e]

[dlg GENERIC_HELP_101]
[s]Spawn NPC models and[n]preview their animations.[e]

[dlg GENERIC_HELP_102]
[s]Change various values[n]in the game's memory.[e]

[dlg GENERIC_HELP_103]
[s]Set a date and time and[n]travel directly to it.[e]

[dlg GENERIC_HELP_104]
[s]Play a movie file, such[n]as an animated cutscene.[e]

[dlg GENERIC_HELP_105]
[s]View your IM messages[n]or auto heal party.[e]

[dlg GENERIC_HELP_106]
[s]Show some info about the[n]development of this mod.[e]

[dlg PlayerMenuName]
Player Options[w][e]

[sel PlayerMenu]
[s]Personas[f 4 26 0 109][e]
[s]Social Stats[f 4 26 1 110][e]
[s]Items[f 4 26 2 111][e]
[s]Set Confidant Rank[f 4 26 3 112][e]
[s]Set Protag Name[f 4 26 4 113][e]
[s]Set Team Name[f 4 26 5 114][e]
[s]Animation Test[f 4 26 6 115][e]
[s]Set Scale[f 4 26 7 116][e]
[s]Attach Item Model[f 4 26 8 117][e]
[s]Max Money[f 4 26 9 118][e]
[s]Max Level[f 4 26 10 119][e]

[dlg GENERIC_HELP_109]
[s]Add or remove your Personas, or[n]give you or your party[n]members new Skills.[e]

[dlg GENERIC_HELP_110]
[s]Add points to your Knowledge,[n]Charm, Proficiency, Guts[n]or Kindness.[e]

[dlg GENERIC_HELP_111]
[s]Give yourself a desired amount of[n]any consumables, weapons, armor,[n]costumes, or even key items.[e]

[dlg GENERIC_HELP_112]
[s]Select a Confidant and set your[n]current rank with their Arcana.[e]

[dlg GENERIC_HELP_113]
[s]Rename the protagonist at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_114]
[s]Change the group name of the[n]Phantom Thieves at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_115]
[s]Select one of the protagonist's[n]Field GAP files and view[n]its animations.[e]

[dlg GENERIC_HELP_116]
[s]Change the size of the[n]selected model.[e]

[dlg GENERIC_HELP_117]
[s]Enter an item's model ID[n]to attach it to the[n]protagonist's right hand.[e]

[dlg GENERIC_HELP_118]
[s]Adds 9,999,999 yen to your[n]wallet.[e]

[dlg GENERIC_HELP_119]
[s]Makes all party[n]members Level 99.[e]

[dlg ItemMenuName]
Select Item Type...[w][e]

[sel ItemMenu]
Consumables[f 4 26 0 122][e]
Accessories[f 4 26 1 123][e]
Key Items[f 4 26 2 124][e]
Ranged Weapons[f 4 26 3 125][e]
Melee Weapons[f 4 26 4 126][e]
Outfits[f 4 26 5 127][e]
Armor[f 4 26 6 128][e]
Materials[f 4 26 7 129][e]
Skill Cards[f 4 26 8 130][e]

[dlg GENERIC_HELP_122]
[s]Items that recover HP & SP,[n]relieve status ailments, or[n]provide buffs or debuffs.[e]

[dlg GENERIC_HELP_123]
[s]Items that you can equip to your[n]party members for stat[n]enhancements.[e]

[dlg GENERIC_HELP_124]
[s]Passive items that are acquired[n]throughout the story.[e]

[dlg GENERIC_HELP_125]
[s]Arms that can be equipped to[n]fire bullets during battle.[e]

[dlg GENERIC_HELP_126]
[s]Weapons used for basic physical[n]attacks during battle.[e]

[dlg GENERIC_HELP_127]
[s]Equippable appearance changes[n]for party members that modify[n]their model in the Metaverse.[e]

[dlg GENERIC_HELP_128]
[s]Equippable items that can boost[n]defense or provide other benefits.[e]

[dlg GENERIC_HELP_129]
[s]Items that can be sold to Iwai[n]or used to create tools.[e]

[dlg GENERIC_HELP_130]
[s]Items that can be used to assign[n]Skills to one of your Personas.[e]

[dlg CommuMenuName]
Select Confidant...[w][e]

[sel CommuMenu]
Igor[f 4 26 0 133][e]
Morgana[f 4 26 1 134][e]
Makoto Niijima[f 4 26 2 135][e]
Haru Okumura[f 4 26 3 136][e]
Yusuke Kitagawa[f 4 26 4 137][e]
Sojiro Sakura[f 4 26 5 138][e]
Ann Takamaki[f 4 26 6 139][e]
Ryuji Sakamoto[f 4 26 7 140][e]
Goro Akechi[f 4 26 8 141][e]
Futaba Sakura[f 4 26 9 142][e]
Chihaya Mifune[f 4 26 10 143][e]
Caroline and Justine[f 4 26 11 144][e]
Munehisa Iwai[f 4 26 12 145][e]
Tae Takemi[f 4 26 13 146][e]
Sayado Kawakami[f 4 26 14 147][e]
Ichiko Ohya[f 4 26 15 148][e]
Shinya Oda[f 4 26 16 149][e]
Hifumi Togo[f 4 26 17 150][e]
Yuuki Mishima[f 4 26 18 151][e]
Toranosuke Yoshida[f 4 26 19 152][e]
Sae Niijima[f 4 26 20 153][e]
Kasumi Yoshizawa[f 4 26 21 154][e]
Takuto Maruki[f 4 26 22 155][e]
Sumire Yoshizawa[f 4 26 23 156][e]

[dlg GENERIC_HELP_133]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fool[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_134]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Magician[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_135]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Priestess[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_136]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Empress[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_137]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Emperor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_138]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Heirophant[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_139]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Lovers[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_140]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Chariot[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_141]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Justice[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_142]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hermit[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_143]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fortune[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_144]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Strength[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_145]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hanged Man[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_146]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Death[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_147]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Temperance[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_148]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Devil[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_149]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Tower[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_150]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Star[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_151]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Moon[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_152]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Sun[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_153]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Judgement[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_154]
[s]Set the desired rank for[n]the Confidant of the [clr 9]World[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_155]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Faith[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_156]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Councillor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_157]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Faith[clr 0][n]Arcana.[e]

[dlg StatsMenuName]
Select Stat Type...[w][e]

[sel StatsMenu]
Knowledge[f 4 26 0 160][e]
Charm[f 4 26 1 161][e]
Proficiency[f 4 26 2 162][e]
Guts[f 4 26 3 163][e]
Kindness[f 4 26 4 164][e]

[dlg GENERIC_HELP_160]
[s]Increase your [clr 26]Knowledge[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_161]
[s]Increase your [clr 26]Charm[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_162]
[s]Increase your [clr 26]Proficiency[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_163]
[s]Increase your [clr 26]Guts[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_164]
[s]Increase your [clr 26]Kindness[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg StatPrompt [Stats]]
Add how many points?[n](max. 2 digits, press Circle to end)[w][e]

[dlg ItemPrompt [Items]]
Enter the item ID you want.[n](max. 4 digits, press Circle to end)[w][e]

[dlg ItemPrompt2 [Items]]
Enter how many items you want.[n](max. 2 digits, press Circle to end)[w][e]

[dlg CmmDialog [Confidant Rank]]
Enter the Confidant's Arcana ID.[n](max. 2 digits, press Circle to end)[w][e]

[dlg CmmDialog2 [Confidant Rank]]
Enter the desired Confidant rank.[w][e]

[dlg AnimMenuName]
Player Animation[w][e]

[sel AnimMenu]
Field Animation Test[e]
Morgana Out of Bag[e]
Morgana In Bag[e]
Show Bag[e]
Hide Bag[e]
Umbrella On[e]
Umbrella Off[e]

[dlg GAPMenuName]
GAP Playback[w][e]

[sel GAPMenu]
Set GAP ID[f 4 26 0 174][e]
Set GAP Index[f 4 26 1 175][e]
Toggle Loop[f 4 26 2 176][e]
Set Speed[f 4 26 3 177][e]
Set Time[f 4 26 4 178][e]
Playback animation[f 4 26 5 179][e]

[dlg GENERIC_HELP_174]
[s]Input the filename of[n]a [clr 9]field GAP file for[clr 0][n]this character. (Starts with [clr 9]af[clr 0])[e]

[dlg GENERIC_HELP_175]
[s]Input the index of the[n]animation from the [clr 26]GAP[clr 0][n]that you want to view.[e]

[dlg GENERIC_HELP_176]
[s]Decide whether you want[n]the animation to repeat or not[n]when it's finished.[e]

[dlg GENERIC_HELP_177]
[s]Decide the playback speed[n]of the animation.[e]

[dlg GENERIC_HELP_178]
[s]Decide how many seconds you[n]would like to play the[n]animation for.[e]

[dlg GENERIC_HELP_179]
[s]Execute the animation playback[n][clr 9]after the above settings[clr 0][n]have been completed.[e]

[dlg ScalePrompt [Scale Model]]
Set the character's model scale.[n](press Circle to end)[n]Default is 10.[w][e]

[dlg CameraMenuName]
Camera Options[w][e]

[sel CameraMenu]
Reposition Camera[f 4 26 0 183][e]
Adjust FOV[f 4 26 1 184][e]
Adjust Zoom[f 4 26 2 185][e]
Rotate Camera[f 4 26 3 186][e]
Unlock Camera[f 4 26 4 187][e]
Lock Camera[f 4 26 5 188][e]
Disable Camera Shake[f 4 26 6 189][e]

[dlg GENERIC_HELP_183]
[s]Move the camera along the X, Y[n]or Z axis. Hold Square to change[n]the axis.[e]

[dlg GENERIC_HELP_184]
[s]Adjust the camera's[n]Field of View.[e]

[dlg GENERIC_HELP_185]
[s]Zoom the camera in[n]and out.[e]

[dlg GENERIC_HELP_186]
[s]Change the orientation of the[n]camera with the D-pad.[e]

[dlg GENERIC_HELP_187]
[s]Make the camera follow the player[n]again if previously locked.[e]

[dlg GENERIC_HELP_188]
[s]Makes the camera stationary,[n]which is required to modify it.[e]

[dlg CalendarMenuName]
Calendar Options[w][e]

[sel CalendarMenu]
Set Next Day[f 4 26 0 191][e]
Call Calendar[f 4 26 1 192][e]
Set Weather[f 4 26 2 193][e]
Loop Current Day[f 4 26 3 194][e]
Go to 3rd Semester[f 4 26 4 195][e]

[dlg GENERIC_HELP_191]
[s]Choose the day and month[n]to warp to.[e]

[dlg GENERIC_HELP_192]
[s]End the current day and warp[n]to the next specified day.[e]

[dlg GENERIC_HELP_193]
[s]Change the current weather[n]condition value. Weather should[n]change after reloading map.[e]

[dlg GENERIC_HELP_194]
[s]Sets the current time[n]of day to be next after[n]ending the current day.[e]

[dlg GENERIC_HELP_195]
[s]Go to the first day[n]of new Royal content.[e]

[dlg CalendarPrompt[Calendar]]
Choose what month to start in.[n](press Circle to end)[w][e]

[dlg CalendarPrompt2 [Calendar]]
Choose what day to start on.[n](max. 2 digits, press Circle to end)[w][e]

[dlg EventDlg [Event Select]]
Choose the first 3 digits of
[n]the event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg EventDlg2 [Event Select]]
Choose the last 3 digits of
[n]the event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg KfEventDlg [KeyFree Event Select]]
Choose the first 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg KfEventDlg2 [KeyFree Event Select]]
Choose the last 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg FieldDlg [Field Select]]
Choose the first 3 digits of
[n]the field to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg FieldDlg2 [Field Select]]
Choose the last 3 digits of
[n]the field to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg SpawnMenuName]
NPC Options[w][e]

[sel SpawnMenu]
Spawn Model[f 4 26 0 206][e]
Animate Model[f 4 26 1 207][e]
Set Model Scale[f 4 26 2 208][e]
Attach Item Model[f 4 26 3 209][e]
Spawn Object Model[f 4 26 4 210][e]

[dlg GENERIC_HELP_206]
[s]Input a [clr 9]GMD filename[clr 0][n]to spawn a character model from.[e]

[dlg GENERIC_HELP_207]
[s]Apply field animations[n]to the last NPC you spawned.[e]

[dlg GENERIC_HELP_208]
[s]Set the scale of the[n]NPC model.[e]

[dlg GENERIC_HELP_209]
[s]Input a [clr 9]GMD filename[clr 0][n]to attach to the NPC.[e]

[dlg GENERIC_HELP_210]
[s]Input a [clr 9]GMD filename[clr 0][n]of an object to spawn.[e]

[dlg PersonaMenuName]
Persona Options[w][e]

[sel PersonaMenu]
Add Persona[f 4 26 0 213][e]
Delete Personas[f 4 26 1 214][e]
Add Skill[f 4 26 2 215][e]
Unlock Full Compendium[f 4 26 3 216][e]
Evolve Persona[f 4 26 4 217][e]

[dlg GENERIC_HELP_213]
[s]Input a Persona's name or ID[n]to add it to your stock.[e]

[dlg GENERIC_HELP_214]
[s]Permanently remove all Personas[n]from your current stock.[e]

[dlg GENERIC_HELP_215]
[s]Choose a party member and the[n]name or ID of a Skill to add[n]to their current Persona.[e]

[dlg GENERIC_HELP_216]
[s]Register every Persona in[n]the game by filling your[n]stock with them all.[e]

[dlg GENERIC_HELP_217]
[s]Evolve a party member's Persona[n]into its Ultimate form.[e]

[dlg UnitMenuName]
Select Party Member[w][e]

[sel UnitSelect]
Joker[e]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]
Yoshizawa[e]

[sel UnitSelect2]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]
Kasumi[e]
Black Mask[e]
Sumire[e]

[sel UnitSelect3]
Ryuji[e]
Morgana[e]
Ann[e]
Yusuke[e]
Makoto[e]
Haru[e]
Futaba[e]
Akechi[e]
Yoshizawa[e]
All[e]

[dlg PersonaDelPrompt [Delete Personas]]
This will permanently remove all 
[n]Personas in your stock. Are you sure?[w][e]

[dlg UnitPrompt [Add Skill]]
Choose a character to add a skill to
[n]their currently equipped Persona.[w][e]

[dlg SkillPrompt [Add Skill]]
Enter the ID of the skill to add.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg PersonaAddPrompt [Add Persona]]
Input the ID of the Persona to add.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg NPCPrompt [Model Select]]
Set the first (4 digits) of the NPC
[n]filename to load. (Press Circle to end)[w][e]

[dlg NPCPrompt2 [Model Select]]
Set the next (3 digits) of the NPC
[n]model filename to load. (Press Circle to end)[w][e]

[dlg NPCPrompt3 [Model Select]]
Set the last (2 digits) of the NPC
[n]model filename to load. (Press Circle to end)[w][e]

[dlg GapPrompt [Animation Test]]
Select the GAP ID.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg GapPrompt2 [Animation Test]]
Select which animation to play.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt3 [Animation Test]]
Select whether to loop or not.[w][e]

[dlg GapPrompt4 [Animation Test]]
Select the third parameter.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt5 [Animation Test]]
Select the animation speed. Default is 10.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt6 [Animation Test]]
Select the number of seconds to play.[w][e]

[dlg CameraPrompt [Camera Mode]]
Use the D-Pad to manipulate the camera.
[n]Press Triangle to quit.
[n](Camera must be locked first!)[w][e]

[dlg SelectBgmDialog [Ultimate DJ TGE]]
Select a bgm to play.[w][e]

[dlg FlagMenuName]
Flag Options[w][e]

[sel FlagMenu]
HUD Display[f 4 26 0 239][e]
Manage Party Members[f 4 26 1 240][e]
Change Romance Route[f 4 26 2 241][e]
Manage Hideout[f 4 26 3 242][e]
Room Editor[f 4 26 4 243][e]
Manual Input[f 4 26 5 244][e]
3rd Semester Stuff[f 4 26 6 245][e]
Mass Flag Editor[f 4 26 7 246][e]

[dlg GENERIC_HELP_239]
[s]Show or hide the user interface[n]elements, such as the date, time,[n]and mission list.[e]

[dlg GENERIC_HELP_240]
[s]Add/remove party members[n]or change the navi.[e]

[dlg GENERIC_HELP_241]
[s]Change the location[n]of the hideout.[e]

[dlg GENERIC_HELP_242]
[s]Start or end a relationship with[n]a female Confidant.[e]

[dlg GENERIC_HELP_243]
[s]Modify the state of the[n]protagonist's bedroom in[n]the Leblanc attic.[e]

[dlg GENERIC_HELP_244]
[s]Enter an 4-digit decimal value[n]of a bit to either[n]enable or disable it.[e]

[dlg GENERIC_HELP_245]
[s]Change values related[n]to Royal content.[e]

[dlg GENERIC_HELP_246]
[s]Manipulate a selected[n]range of bit flags to[n]toggle or print.[e]

[dlg PartyFlagMenuName]
Party Flags[e]

[sel PartyFlagMenu]
Add Party Members[f 4 26 0 249][e]
Remove Party Members[f 4 26 1 250][e]
Enable Party Editing[f 4 26 2 251][e]
Add Overworld Follower[f 4 26 3 252][e]
Toggle Showtimes[f 4 26 4 253][e]
Change Navigator[f 4 26 5 254][e]

[dlg GENERIC_HELP_249]
[s]Make a Persona user[n]available for your party.[e]

[dlg GENERIC_HELP_250]
[s]Revoke a Persona user's[n]availability in[n]your party.[e]

[dlg GENERIC_HELP_251]
[s]Allow choosing your[n]party from Stats in[n]the pause menu.[e]

[dlg GENERIC_HELP_252]
[s]Enable or disable party[n]members following you[n]in the overworld.[e]

[dlg GENERIC_HELP_253]
[s]Enable or disable[n]party member Showtimes.[e]

[dlg GENERIC_HELP_254]
[s]Change which character[n]serves as  Navigator.[e]

[dlg FieldMenuName]
Field Select[e]

[sel FieldMenu]
Enter Field ID[f 4 26 0 257][e]
Load Field[f 4 26 1 258][e]
Reload Current Field[f 4 26 2 259][e]

[dlg GENERIC_HELP_257]
[s]Input the 6 digits of a[n][clr 9]field pack's[clr 0] filename[n](found in ps4R.cpk/field)[e]

[dlg GENERIC_HELP_258]
[s]Attempt to load the selected[n]field. [clr 9]WARNING: Some fields may[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_259]
[s]Reload the field that[n]you're currently on.[e]

[dlg EventMenuName]
Event Select[e]

[sel EventMenu]
Enter Event ID[f 4 26 0 262][e]
Load Event[f 4 26 1 263][e]
Enter KeyFree Event ID[f 4 26 2 264][e]
Load KeyFree Event[f 4 26 3 265][e]

[dlg GENERIC_HELP_262]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](found in dataR.cpk/event)[e]

[dlg GENERIC_HELP_263]
[s]Attempt to load the selected[n]event. [clr 9]WARNING: Some events may[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_264]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](found in ps4R.cpk/field).[clr 0][e]

[dlg GENERIC_HELP_265]
[s]Attempt to load the selected[n]KeyFree event. [clr 9]WARNING: Some events may[n]softlock the game.[clr 0][e]

[dlg NaviMenuName]
Select Navigator[w][e]

[sel NaviMenu]
Morgana[e]
Futaba[e]
Akechi[e]
None[e]

[dlg HideoutMenuName]
Select Hideout[w][e]

[sel HideoutMenu]
School Rooftop[e]
Shibuya Walkway[e]
Leblanc Floor 2[e]
Leblanc Floor 1[e]

[dlg ShowtimeMenuName]
Toggle Showtimes[w][e]

[sel ShowtimeMenu]
Ann/Mona[e]
Morgana/Haru[e]
Ann/Yusuke[e]
Ryuji/Yusuke[e]
Ryuji/Makoto[e]
Joker/Akechi[e]
Makoto/Haru[e]
Joker/Kasumi[e]

[dlg ThirdSemesterMenuName]
3rd Semester Flags[w][e]

[sel ThirdSemesterMenu]
Sumire Name (Party)[e]
Sumire Route (Coop)[e]
Sumire Appearance[e]

[sel DateDisplayDlg]
Enable[e]
Disable[e]

[dlg LoveMenuName]
Select Relationship[w][e]

[sel LoveMenu]
Makoto[e]
Haru[e]
Ann[e]
Futaba[e]
Chihaya[e]
Takemi[e]
Kawakami[e]
Ohya[e]
Hifumi[e]
Sumire[e]

[dlg AboutDlg[About this menu]]
Created by [clr 1]TGE[clr 0], [clr 6]ShrineFox[clr 0]
[n]and [clr 9]CaptainSwag101[clr 0] using TGE's 
[n]AtlusScriptCompiler tool.[w][e]
Special thanks to [clr 1]@regularpanties[clr 0]
[n]for providing a 6.72 PS4 for testing and
[n][clr 9]RayFirefist[clr 0] for menu improvements.[w][e]
Visit [clr 1]amicitia.github.io[clr 0]
[n]to learn more![w][e]

[sel RoomEdit]
Furniture[e]
Collectibles[e]
Cleanliness[e]

[sel FurnEdit]
Plant[e]
Sayuri[e]
DVD Player[e]
Game Console[e]
Old TV Set[e]
Radio[e]
Cat Bed[e]
UFO Game Prizes...[e]

[sel CollEdit]
Swan Boat[e]
Ramen[e]
Pennant[e]
Statue[e]
Sky Tree[e]
Big Hera[e]
Shumai[e]
Fusen[e]
I Love[e]
Idol[e]
More...[e]

[sel CollEdit2]
Seiza[e]
Syogi[e]
Hero[e]
Hamaya[e]
Jyainyan[e]
Sushi[e]
Choco[e]
Kumade[e]
Prev...[e]

[sel CleanEdit]
Bookshelf[e]
Workbench[e]
Visitor Table[e]
Training Chair[e]
Winter Heater[e]
Laptop[e]

[dlg MonthMenuName]
Select a Month[e]

[sel MonthMenu]
January[e]
February[e]
March[e]
April[e]
May[e]
June[e]
July[e]
August[e]
September[e]
October[e]
November[e]
December[e]

[dlg CalendarError]
Invalid day selected.[n]
Please try again.[w][e]

[dlg CalendarBackwardsError]
You can only go back one day at a time.[w][e]

[dlg BossTypeName]
Palace Boss Select[w][e]

[sel BossType]
Manual Entry[w][e]
By Palace[w][e]

[dlg SelectBossName]
Boss Event Select[w][e]

[sel Palace1]
Battle Scenario 1[e]
Battle with Morgana[e]
Battle Scenario 2[e]
Battle Scenario 3[e]
Sub Battle 1[e]
Sub Battle 2[e]
Gun Tutorial[e]
Hold Up Tutorial[e]
All Out Attack Tutorial[e]
Persona Recruit Tutorial[e]
Mini Boss 1[e]
Mini Boss 2[e]
Shadow Kamoshida[e]

[sel Palace2]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Battle Scenario[e]
Shadow Madarame[e]

[sel Palace3]
Battle Scenario[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Mini Boss 5[e]
Shadow Kaneshiro[e]

[sel Palace4]
Bandit[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Wakaba[e]

[sel Palace5]
Cognitive Sugimura[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Okumura[e]

[sel Palace6]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3 (05_B)[e]
Mini Boss 4 (05_BOSS)[e]
Akechi's First Battle[e]
Mini Boss (Dark Zone)[e]
Mini Boss (Camera Room)[e]
Mini Boss (Dice)[e]
Slot (ENYRY) Battle[e]
Escape Battle[e]
Shadow Sae[e]

[sel Palace7]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
First Target[e]
Second Target[e]
Third Target[e]
Fourth Target[e]
Fifth Target[e]
Akechi[e]
Shadow Shido[e]

[sel Palace8]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
The Holy Grail[e]
The Twins[e]
Uriel[e]
Raphael[e]
Gabriel[e]
Michael[e]
Yaldabaoth[e]

[sel Misc1]
Prologue Battle[e]
QUEST_BATTLE[e]
Yusuke Co-op[e]
int_CLEAR[e]
ALERT_CLEAR_EX[e]
PALACE_CLEAR_SYS[e]
PALACE_CALL_CALENDAR[e]
Closest encounter to position[e]
D_ENCOUNT_START[e]
dungeon_return_calendar[e]
dungeon_return[e]
Next[e]

[sel Misc2]
dungeon_exit_time_set[e]
dungeon_start_format[e]
DUNGEON_START_SAVE[e]
result_counter_clear[e]
MVP_CHOICE (CRASH!)[e]
D_ENCOUNT_NO_GET[e]
Dummy[e]
Dummy[e]
Previous[e]

[dlg HudTest1]
HUD has been enabled.[w][e]

[dlg HudTest2]
HUD has been disabled.[w][e]

[dlg PersonaAdded]
The chosen Persona has been[n]added to your stock.[w][e]

[dlg PersonaDeleted]
All Personas have been deleted.[w][e]

[dlg WeatherChanged]
Weather has been changed.[w][e]

[dlg LoadCheckError]
Set the required parameters[n]before attempting to load![w][e]

[dlg WeatherMenuName]
Weather Select[w][e]

[sel WeatherMenu]
Sunny[e]
Rainy[e]
Cloudy[e]
Snow[e]
Rainy Season[e]
Typhoon Warning[e]
Sunny Pollen Warning[e]
Cloudy Pollen Warning[e]
Torrential Rain[e]
Sunny Heatwave/Hot Night[e]
Sunny Flu Season[e]
Cloudy Flu Season[e]

[dlg BattleTypeName]
Battle Type Select[w][e]

[sel BattleTypeMenu]
Regular Encounter[e]
Boss Encounter[e]
Event Battle[e]

[dlg EventBattleName]
Battle Type Select[w][e]

[sel PalaceMenu]
Castle[e]
Art Museum[e]
First World Bank[e]
Pyramid[e]
Space Station[e]
Casino[e]
Cruise Ship[e]
Mementos Depths[e]
Misc[e]

[dlg PalaceName]
Palace Select[e]

[sel EventBattleSelect]
Akechi[e]
Akechi Phase 2[e]
Holy Grail[e]
Yaldabaoth[e]
Velvet Twins[e]
MISC[e]

[dlg EncounterPrompt]
Set the number of the encounter[n]you want to fight (4 digits).[w][e]

[sel FlagMassEditor]
Disable all flags[e]
Enable all flags[e]
Swap enabled/disabled flags[e]
Toggle range of flags[e]
Clear Inherit Data[e]

[dlg PersonaAddSkillMenuName]
Persona Options[w][e]

[sel PersonaAddSkillMenu]
Add Skill[e]
Add Skill (Manual Input)[e]

[dlg PersonaAddMenuName]
Persona Options[w][e]

[sel PersonaAddMenu]
Add Persona[e]
Add Persona (Manual Input)[e]

[dlg BagShowHide]
The bag has been toggled.[n]To see the change, go to a new field[n]or reload the current one.[w][e]

[dlg GENERIC_HELP_321]
Removes swaying effect[n]of the camera used[n]in dungeons.[w][e]

[dlg GENERIC_HELP_322]
Select an item's model ID to[n]spawn it and connect it to[n]the character's model.[w][e]

[dlg GENERIC_HELP_323]
Select a range of flags[n]to either enable or disable.[w][e]

[dlg ItemSpawnPrompt]
Enter the first half of the model's[n]ID from dataR.cpk/model/item.[n](Max 4 digits, press Circle to end).[w][e]

[dlg ItemSpawnPrompt2]
Enter the last half of the model's[n]ID from dataR.cpk/model/item.[n](Max 3 digits, press Circle to end).[w][e]

[dlg ObjectSpawnPrompt]
Enter the first half of the[n]model's ID from dataR.cpk/model/field_tex/object.[n](Max 3 digits, press Circle to end).[w][e]

[dlg ObjectSpawnPrompt2]
Enter the last half of the[n]model's ID from dataR.cpk/model/field_tex/object.[n](Max 3 digits, press Circle to end).[w][e]

[dlg FlagRangePrompt]
Enter the start of the[n]range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[dlg FlagRangePrompt2]
Enter the end of the[n]range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[dlg GENERIC_HELP_330]
Unlocks all Personas in the[n]Compendium. [clr 9]This will delete all[n]Personas in your current stock![clr 0][w][e]

[dlg MoviePlayPrompt[Movie Select]]
Insert the Movie ID to play.[n](Max 3 digits, press Circle to end)[w][e]

[dlg ManualBossFightPrompt[Movie Select]]
Insert the Boss ID to play.[n](Max 2 digits, press Circle to end)[w][e]